### ISSUE TITLE
MongoDB connection error: MongoParseError: Invalid connection string

### ISSUE THREAD

**Issue by lefflo** [Icesofty/shopster#3]
I follow the tutorial on Atlas. The cluster is running, robo3t is running fine but whenever I hit npm start, it gives this error.

This also happens if I click on the login button :+1: 

`::ffff:127.0.0.1 - - [04/Nov/2020:00:11:56 +0000] "POST /users/login HTTP/1.1" - - "http://localhost:3000/users/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
`
Here's the detailed log ;

``> nodejs-mvc-ecommerce@1.0.0 start /home/mathieu/projects/techproject/shopster
> node server.js

Server listening on port 3000
MongoDB connection error: MongoParseError: Invalid connection string
    at parseConnectionString (/home/mathieu/projects/techproject/shopster/node_modules/mongodb/lib/core/uri_parser.js:565:21)
    at connect (/home/mathieu/projects/techproject/shopster/node_modules/mongodb/lib/operations/connect.js:282:3)
    at /home/mathieu/projects/techproject/shopster/node_modules/mongodb/lib/mongo_client.js:223:5
    at maybePromise (/home/mathieu/projects/techproject/shopster/node_modules/mongodb/lib/utils.js:662:3)
    at MongoClient.connect (/home/mathieu/projects/techproject/shopster/node_modules/mongodb/lib/mongo_client.js:219:10)
    at /home/mathieu/projects/techproject/shopster/node_modules/mongoose/lib/connection.js:791:12
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/home/mathieu/projects/techproject/shopster/node_modules/mongoose/lib/connection.js:788:19)
    at /home/mathieu/projects/techproject/shopster/node_modules/mongoose/lib/index.js:342:10
    at /home/mathieu/projects/techproject/shopster/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/mathieu/projects/techproject/shopster/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose.connect (/home/mathieu/projects/techproject/shopster/node_modules/mongoose/lib/index.js:341:10)
    at Object.<anonymous> (/home/mathieu/projects/techproject/shopster/models/ProductModel.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10) {
  name: 'MongoParseError'`

**Comment by florianjs** [comment]
@lefflo it means you have a wrong mondb URL
On Cloud Atlas => under your CLuster click on 'Connect' => 'Connect your application' => Copy the URL (begin with mongodb:// ... )

Replace <password> with the password for the <username> user. Replace <dbname> with the name of the database that connections will use by default.

Paste the URL in DB_URL= into your .env file

**Comment by lefflo** [comment]
Worked great! thank you.
